name: Run Update All Members

on:
  workflow_dispatch:   # allows manual trigger
  schedule:
    - cron: "*/5 * * * *"  # automatic run every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run update script
        env:
          MEMBERS_API: ${{ secrets.MEMBERS_API }}
        run: |
          mkdir -p attacks
          python3 update_all_members.py

      - name: Commit and push updated attacks
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add attacks/*.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update attacks JSON"
            git push
          fi
